config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "application#landing"
  # root to: "restaurants#index"
  # get "restaurants", to: "restaurant#index", as: "root"
  get "restaurant/:id", to: "restaurants#show", as: "restaurant_show"
  get "restaurant/:id/checkout", to: "restaurants#checkout", as: "restaurant_checkout"
  # post "restaurant/:id/checkout", to: "restaurants#checkout_confirm", as: "restaurant_checkout"
  post "restaurant/:id", to: "restaurants#create", as: "restaurant_new" 
  post "restaurant/:id", to: "restaurants#update", as: "restaurant_edit" 
  post "restaurant/:id", to: "restaurants#destroy", as: "restaurant_delete"
  post "restaurant/:id", to: "restaurants#order_meal", as: "restaurant_order_meal"

  get "meal/:id", to: "meals#show", as: "meal_show"
  post "meal/:id", to: "meals#create", as: "meal_new" 
  post "meal/:id", to: "meals#update", as: "meal_edit" 
  post "meal/:id", to: "meals#destroy", as: "meal_delete"

  post "restaurant/:id/checkout", to: "orders#create", as: "order_add" 
  get "order/:id", to: "orders#show", as: "order_show"
  post "order/:id", to: "orders#update", as: "order_edit" 
  post "order/:id", to: "orders#destroy", as: "order_delete"

  
  get "users/:username/profile", to: "users#user_profile", as: "user_profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :restaurant
    has_many :orders, through: :restaurant
    validates :name, presence: true
    validates :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
    # validates :name, presence: true
    # validates :description, presence: true
    # validates :capacity, presence: true , length: { minimum: 0 }
    validates :date, presence: true
    # validates :phone_number, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :meals, dependent: :delete_all
    has_many :orders, dependent: :delete_all
     
    validates :name, presence: true
    validates :description, presence: true
    # validates :capacity, presence: true , length: { minimum: 0 }
    # validates :date, presence: true
    validates :contact, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def landing
        render "homepage/home"
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController  
  def index
        @meals = Meal.all
      end
    
      def show
        @meal = Meal.find(params[:id])
      end
    
      def create
        @new_meal = Meal.new(meal_params)
        if @new_meal.save
          # render json: { status: 'success'}
          render json: @new_meal
        else
          render json: { status: 'fail'}, status: 400
          # render error
        end
      end
    
      def update
        @meal.update(room_params)
      end
    
      def destroy 
        @meal.destroy
      end
    
      private
      #Meal id: nil, name: nil, description: nil, meal_img_url: nil, price: nil, created_at: nil, updated_at: nil, restaurant_id: nil
      def set_meal
        @meal = Meal.find(params[:id])
    
      end
      def meal_params
        params.require(:meal).permit(:id, :name, :price, :description, :meal_img_url, :restaurant_id)
      end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_order, only: :show 
      def index
        @orders = Order.all
      end
    
      def show
        @order = Order.find(params[:id])
      end
    
      def create
        @new_order = Order.new(order_params)
        @new_order.id = nil
 
        if @new_order.save
          flash[:notice] = " #{Meal.find(order_params[:meal_id]).name} added to cart"
          @res = true
          p "success!"
          flash[:notice] = "order complete"

        else
          
          @res = false
        end
    
        p "create called end"
      end
      def cart

      end
    
      def update
        @order.update(order_params)
      end
    
      def destroy 
        @order.destroy
      end
    
      private
      #<Order id: nil, date: nil, quantity: nil, created_at: nil, updated_at: nil, restaurant_id: nil, meal_id: nil
      def set_order
        @order = Order.find(params[:id])
    
      end
      def order_params
        params.permit(:id,:date, :quantity, :restaurant_id, :meal_id, :user_id)
      end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [ :checkout]
  before_action :set_restaurant
  
  def index
    @restaurants = Restaurant.all
  end

  def checkout
      @resaurrant = Restaurant.find(params[:id])
      @meal = Meal.find(params[:meal])
      @date = DateTime.now()
      @user = current_user
      set_flash_notice = "order complete"
  end
  
  def show

    @restaurant
    p "show was triggered"

  end

  def create
    @new_restaurant = Restaurant.new(restaurant_params)
    if @new_restaurant.save
      # render json: { status: 'success'}
      # render json: @new_restaurant
    else
      # render json: { status: 'fail'}, status: 400
      # render error
    end
  end

  def update
    @restaurant.update(room_params)
  end

  def destroy 
    @restaurant.destroy
  end

  private
  # #Restaurant id: nil, name: nil, description: nil, restaurant_img_url: nil, tables: nil, location: nil, contact: nil, avail_tables: nil
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  def restaurant_params
    params.require(:restaurant).permit(:id, :name, :location, :description, :restaurant_img_url, :tables, :avail_tables, :contact)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user 
    def index
      @users = User.all
    end

    def login
      render "devise/sessions/new"
    end

    def user_profile
      @order_history = @user.orders

    end
  
    def show
      @user = User.find(params[:id])
    end
  
    def create
      @new_user = User.new(user_params)
      if @new_user.save
        # render json: { status: 'success'}
        # render json: @new_user
      else
        # render json: { status: 'fail'}, status: 400
        # render error
      end
    end
  
    def update
      @user.update(room_params)
    end
  
    def destroy 
      @user.destroy
    end
  
    private
    #user id: nil, name: nil, description: nil, user_img_url: nil, tables: nil, location: nil, contact: nil, avail_tables: nil
    def set_user
      @user = current_user
  
    end
    def user_params
      params.require(:user).permit(:id, :name, :location, :description, :user_img_url, :tables, :avail_tables, :contact)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/home.html.erb
<%= render partial: "restaurants/restaurant_index", locals:{restaurants: Restaurant.all, card_path:"shared/cards/meal_card"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
        <%= render partial: "navbar/navbar" %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main>
      <%= yield %>
    </main>
 
  </body>
</html>

app/views/meals/index.html.erb
<h1>Meals#index</h1>

<div class= "meal-index">
    <div class="meals">
      <ul>
      <% @meals.each do |meal| %>
        <li><%= meal.id %>.<%= link_to meal.name, meal_show_path(@meal, id:meal.id) %></li>
      <% end %>
      </ul>
    </div>
</div>

app/views/meals/show.html.erb
<div class="back-icon">
  <p><h2><%= link_to "<", restaurant_show_path(@restaurants, id:@meal.restaurant_id) %></h2></p>
</div>

<div class= "meal-show">
    <div class="meal">
      <ul>
        <li><h1><%= @meal.id %>.<%= @meal.name %></h1></li>
      </ul>
      <p><%= @meal.description %></p>
 
      <%= image_tag @meal.meal_img_url %>
      <p><%= @meal.price %></p>
      <button onclick="btn_click()"class="book-btn" style="font-weight: bold;">+</button>
    </div>
    
</div>

app/views/navbar/_navbar.html.erb
<div class="nav-container"style="display:flex; justify-content: space-around; border-bottom: 1px solid black; box-shadow: 1px grey" >
    
    <div class="menu">
        menu
    </div>
    <div class="title-card">
        Dinners'
    </div>
    <div class="cart">
        cart=0
    </div>
    <div class="user-profile">
        <%= render "users/login" %>
    </div>
</div>

app/views/orders/index.html.erb
<h1>Restaurant#index</h1>

<div class= "restaurant-index">
    <div class="restaurants">
      <ul>
      <% @restaurants.each do |res| %>
        <li><%= res.id %>.<%= link_to res.name, show_path(@restaurant, id:res.id) %></li>
      <% end %>
      </ul>
    </div>
</div>

app/views/orders/show.html.erb
<div class="back-icon">
  <p><h2><%= link_to "<", root_path %></h2></p>
</div>

<div class= "restaurant-show">
    <div class="restaurant">
      <ul>
        <li><h1><%= @restaurant.id %>.<%= @restaurant.name %></h1></li>
      </ul>
      <p><%= @restaurant.description %></p>
 
      <%= image_tag @restaurant.restaurant_img_url %>
      <button onclick="btn_click()"class="book-btn">Open Modal</button>
    </div>
    
</div>


<script>
  function btn_click() {
    alert("Boked");
    
  }
</script>

app/views/restaurant/index.html.erb
<h1>Restaurant#index</h1>
<p>Find me in app/views/restaurant/index.html.erb</p>
<div class= "restaurant-index">
    <div class="restaurants">
      <ul>
      <% @restaurants.each do |res| %>
        <li><%= res.id %>.<%= link_to res.name, show_path(@restaurant, id:res.id) %></li>
      <% end %>
      </ul>
    </div>
</div>

app/views/restaurants/_restaurant_index.html.erb
<h1>Restaurant#index</h1>

<div class= "restaurant-index">
    <div class="restaurants">
      <% restaurants.each do |res| %>
        <div id = <%= res.id%> class="card-category">
            <div class="card-head">
              <div class="card-img">
                <%= image_tag res.restaurant_img_url, alt:"restaurant image" %>
              </div>
            </div>
            <div class="card-content">
              <div class="card-res">
                <div class="card-res-name">
                  <%= link_to res.name, restaurant_show_path(@restaurants, id:res.id) %>

                </div>
                <div class="card-res-loc">
                  <%= res.location%>
                </div>
              </div>
              <%if local_assigns[:card_path] != nil%>
                <div class="card-meals">
                  <%res.meals[0..3].each do |meal|%>
                      <%= render partial: card_path, locals:{meal: meal} %>
                  <%end%>
                </div>

              <%else%>
                <div class="div"></div>
              <%end%>
            </div>
        </div>
      <% end %>
    </div>
</div>

app/views/restaurants/checkout.html.erb
<div class="back-icon">
  <p><h2><%= link_to "<", restaurant_show_path %></h2></p>
</div>
<div class="checkout-header">
    Checkout 
</div>
<div class="flash-msg">
  <%= flash.now[:notice] %>
</div>
<div class="checkout-container" style="display:flex; flex-direction:column; justify-content:center; align-items:center;">
  <%= form_with(model: @order_add_path) do |f| %>
    <div class="checkout-content" style="display:flex; flex-direction:column; justify-content:space-around; padding:20px;">
      <div class="restaurant-content" style="display:flex; justify-content:space-between;">
        <%= f.label :restaurant_id %>
        <%= f.text_field :restaurant_id, :value => @restaurant.id, :disabled => true %>
      </div>
      
  
      <div class="user-content" style="display:flex; justify-content:space-between; align-items:center">
        <div class="user-info" style="display:flex; justify-content:space-around;">
          <%= f.label :user_id %>
          <%= f.text_field :user_id, :value => @user.id, :disabled => true %>
        </div>
        <div class="date-info" style="display:flex; justify-content:space-around;">
          <%= f.label :date %>
          <%= f.text_field :date, :value => DateTime.now(), :disabled => true %>
        </div>
      </div>

      
      <div class="meal-content" style="display:flex; justify-content:space-between; align-items:center">
        <div class="meal-info" style="display:flex; justify-content:space-around;">
          <%= f.label :meal_id %>
          <%= f.text_field :meal_id, :value => @meal.id, :disabled => true %>
          <%= f.label :meal_name %>
          <%= f.text_field :meal_name, :value => @meal.name, :disabled => true %>
        </div>
        
        <div class="quantity-info" style="display:flex; justify-content:space-around;">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => 1 %>
        </div>
        
      </div>
      
      
      <div class="submit-btn">
        <%= submit_tag("Checkout") %>
      </div>
    </div>
  <% end %>

</div>

app/views/restaurants/index.html.erb
<h1>Restaurant#index</h1>

<div class= "restaurant-index">
    <div class="restaurants">
      <ul>
      <% @restaurants.each do |res| %>
        <div class="card-category">
          <div>
            <%= link_to res.name, restaurant_show_path(@restaurants, id:res.id) %>
          </div>
        </div>
      <% end %>
      </ul>
    </div>
</div>

app/views/restaurants/show.html.erb
<div class="back-icon">
  <p><h2><%= link_to "<", root_path %></h2></p>
</div>

<div class= "restaurant-show">
    <div class="restaurant-info">
      <ul>
        <li>
          <h1><%= @restaurant.id %>.<%= @restaurant.name %></h1>
        </li>
      </ul>
      <p><%= @restaurant.description %></p>
 
      <%= image_tag @restaurant.restaurant_img_url %>
    </div>
    <div class="card-meals">
      <% @restaurant.meals.each do |meal| %>
          <%= render partial: "shared/cards/meal_card", locals:{meal: meal, others: {check_out: true}} %>
      <% end %>
    </div>    
</div>

<%
=begin%>
 <button onclick="btn_click('<%= meal.name %>')"class="book-btn" style="font-weight: bold;">+</button> 
<%
=end%>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/cards/_meal_card.html.erb
<div class="card-meal">
    <div class="card-meal-img">
    <%= image_tag meal.meal_img_url, alt:"meal image" %>
    </div>
    <div class="card-meal-content">
        <div class="card-meal-name">
            <%= link_to meal.name.length > 8 ? meal.name.slice(0..8)+'...' : meal.name, meal_show_path(@meals, id:meal.id) %>
        </div>
        <div class="card-meal-price">
            <%= meal.price%>
            <%if local_assigns[:check_out] != nil%>
                <div class="btn">
                    <%= link_to "+", restaurant_checkout_path(meal: meal)%>
                </div>
            <%end%>
        </div>
        <%if local_assigns[:description] != nil %>
            <div class="card-meal-des">
                <%= description%>
            </div>
        <%end%>
    </div>

</div>

app/views/users/_login.html.erb
<% if user_signed_in? %>
    <div class="logged-in">
        Hello, <%= link_to current_user.email, user_profile_path(username: {tag: current_user})%>!
    </div>
    <div class="sign-out">
        <%= button_to "sign out", destroy_user_session_path , method: :delete%>
    </div>
<% else %>
    <div class="login">
        <%= link_to "sign in", user_session_path%>
    </div>
<%end%>

app/views/users/user_profile.html.erb
<div class="user-profile">
    <div class="back-icon">
        <p><h2><%= link_to "<", root_path %></h2></p>
    </div>
    <% if user_signed_in? %>
        <div class="logged-in">
            Hello, <%= @user.email%>!
        </div>
        <div class="sign-out">
            <%= button_to "sign out", destroy_user_session_path , method: :delete%>
        </div>
        <div class="order-history">
            <h2>Here is your order history</h2>
            <%if @order_history.length<1%>
                <div class="no-order_history">
                    <h2>You have no recent orders</h2>
                </div>
            <%else%>
                <ul>
                    <% @order_history.each do |order|%>
                        <li>
                            <%= Meal.find(order.meal_id).name%>
                        </li>
                    <%end %>
                </ul>
            <%end%>
                
        </div>
    <% else %>
        <div class="login">
            <%= link_to "sign in", user_session_path%>
        </div>
    <%end%>
</div>